### PR TITLE
A shadow PR to add shapefile support

### PR DESCRIPTION
**Pull request by arjxn-py**
Related to https://github.com/QuantStack/jupytergis/issues/35

https://github.com/user-attachments/assets/ba0d5bac-f94e-4817-883a-9914004b4ab5

Sample data that's been loaded: 
- [https://www2.census.gov/geo/tiger/GENZ2015/shp/cb_2015_us_county_500k.zip](https://www2.census.gov/geo/tiger/GENZ2015/shp/cb_2015_us_county_500k.zip)
- [https://docs.geoserver.org/stable/en/user/_downloads/30e405b790e068c43354367cb08e71bc/nyc_roads.zip](https://docs.geoserver.org/stable/en/user/_downloads/30e405b790e068c43354367cb08e71bc/nyc_roads.zip)

### CODE REVIEW

**Comment by arjxn-py** [comment]
image
A custom shapefile loaded (static currently)

**Comment by arjxn-py** [comment]
@martinrenou would it be a good idea to open this upstream?
Knowing that I'm using a proxy url to avoid CORS error right now and it's a little buggy at the moment (please notice the console)
I'd also not really mind to keep it as is and let a senior developer add support for shapefile.


https://github.com/user-attachments/assets/c22b2d86-45a2-436f-91ba-dd084aafe2f3

**Comment by martinRenou** [comment]
> @martinRenou would it be a good idea to open this upstream?

That would be great! If you don't mind. Amazing work by the way!

We can discuss the CORS issues there

**Comment by arjxn-py** [comment]
> That would be great! If you don't mind. Amazing work by the way!
> 
> We can discuss the CORS issues there

Thanks, I'd love to do that

**Comment by arjxn-py** [comment]
Superseded by https://github.com/QuantStack/jupytergis/pull/104

**Pull request closed without merging**
